[package]
name = "getmal"
version = "0.1.0"
authors = ["Val Saven <val.saven@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.3"
roxmltree = "0.9.1"
select = "0.4.3"
